server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankms
    username: admin
    password: root
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"

build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Hari - Developer"
    email: "hariprasanthirah@gmail.com"
  onCallSupport:
    -9944641234
    -9944645678