services:
  accounts:
    image: "hari3377/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      - postgresDB
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDB:5432/bankms
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  loans:
    image: "hari3377/loans:s1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      - postgresDB
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDB:5432/bankms
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  cards:
    image: "hari3377/cards:s1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      - postgresDB
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDB:5432/bankms
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  postgresDB:
    container_name: postgres_containers
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    restart: unless-stopped
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin_containers
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    restart: unless-stopped
networks:
  eazybank:
    driver: bridge
volumes:
  postgres:
  pgadmin: