spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Ram - QA Lead"
    email: "ram@gmail.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467