server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankms
    username: admin
    password: root
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update