spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Rishi - Product Owner"
    email: "rishi@gmail.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956